language: generic

sudo: required # super user

services:
    - docker # travis install a copuy of docker

before_install:
    - docker build -t falcopellegrino/docker-react -f Dockerfile.dev . # tag here is only for testing environment, could use anything

script:
    - docker run -e CI=true falcopellegrino/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2" #DockerReact-env.eba-w9y4gvrp.us-east-2.elasticbeanstalk.com 
    name: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-356166853548"
    bucket_path: "docker-react"
    on:
        branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        #access_key_id: $AWS_ACCESS_KEY
        #secret_access_key:
        #    secure: "$AWS_SECRET_KEY"